name: Run all tests

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
  workflow_call:  # Allows other workflows to call this setup

jobs:
  Setup_and_Debugs: 
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.8

      - name: Cache Dependencies
        id: CacheStep
        uses: actions/cache@v3
        env: 
          cache-name: absa-auto-env
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install Dependencies and Spacy Model
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_md
          pip install -e . 
      
      # Debug
      - name: Debug Check -> Disply Installed SpaCy Models
        run: python -m spacy validate

      - name: Debug Check -> List ASUC Explore
        run: pip list | grep ASUCExplore

      - name: Debug Check -> Disply Installed Packages
        run: pip list
    
      - name: Debug Check -> Confirm ASUCExplore is recognizeable
        run: python -c "import ASUCExplore; print('ASUCExplore is recognized!')"

      - name: Debug Check -> Disply Python Path
        run: python -c "import sys; print(sys.path)"
      
      - name: Debug Check -> Test Pathing
        run: python Tests/PathingTests.py
  
  Test_Utils_and_Cleaning:
    runs-on: ubuntu-latest
    needs: Setup_and_Debugs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.8

      - name: Cache Dependencies
        id: CacheStep
        uses: actions/cache@v3
        env: 
          cache-name: absa-auto-env
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install Dependencies and Spacy Model
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_md
          pip install -e . 

      - name: Run UtilsTests.py Tests
        run: python Tests/UtilsTests.py

      # - name: Run Cleaning.py Tests
      #   run: python Tests/CleaningTests.py
      
  # Test_Core: 
  #   runs-on: ubuntu-latest
  #   needs: Test_Utils_and_Cleaning
  #   steps: 
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Setup Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.11.8

  #     - name: Cache Dependencies
  #       id: CacheStep
  #       uses: actions/cache@v3
  #       env: 
  #         cache-name: absa-auto-env
  #       with:
  #         path: ~/.cache/pip
  #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pip

  #     - name: Install Dependencies and Spacy Model
  #       run: | 
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #         python -m spacy download en_core_web_md
  #         pip install -e . 

  #     - name: Run PipelineFicommTests.py Tests
  #       run: python Tests/PipelineFicommTests.py

  #     - name: Run PipelineFRTests.py Tests
  #       run: python Tests/PipelineFRTests.py

  #     - name: Run PipelineOASISTests.py Tests
  #       run: python Tests/PipelineOASISTests.py

  #     - name: Run PipelineTests.py Tests
  #       run: python Tests/PipelineTests.py